apiVersion: v1
kind: Service

metadata:
  name: incident-intelligence-service

spec:
  type: NodePort

  selector:
    app: incident-intelligence

  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP

